### Send POST request with json body
POST http://localhost:8081/parquets
Content-Type: application/json

{
  "name": "Test parquet",
  "model": "CLASSIC",
  "price": 120.20,
  "size": 8,
  "classRate": 10,
  "imageUrl": "imageUrl"
}